spring:
  application:
    name: lojavirtual
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #postgres:
  datasource:
    url: jdbc:postgresql://localhost:5432/lojavirtual
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver